module.exports = {

  ActionTypes: {
    FILTER_ADD: 'FILTER_ADD',
    FILTER_REMOVE: 'FILTER_REMOVE',
    FILTER_TOGGLE: 'FILTER_TOGGLE',

    SUBTITLES_GET: 'SUBTITLES_GET',
    SUBTITLES_RESET: 'SUBTITLES_RESET',
  }

};
